### ISSUE TITLE
libEGL.dll: Not a valid win32 application.

### ISSUE THREAD

**Issue by taurusxin** [Ruinscraft/mcef-codec-patch#1]
Windows 10, Using mcef 1.30 (not 1.31)
After patching, ran the game, then got this error.
I compared the two files, it seems that the patched one is much smaller.

In other words, this project has not yet been fully released, and I started acting too early?

**Comment by ds58** [comment]
Yeah, I wasn't quite finished. I have to recreate the diffs for windows

**Comment by ds58** [comment]
Alright, I've updated the diffs for Windows.

In order for this to work, you should launch MC with MCEF 1.31 first (I updated the non-codec binaries just now). It will redownload the binaries.

Then, run mcef-codec-patch and apply the patches.

Make sure the skipUpdates option is set to true in the MCEF config (.minecraft/config/mcef.cfg)

You should now have proprietary codecs enabled.

**Comment by taurusxin** [comment]
> Alright, I've updated the diffs for Windows.
> 
> In order for this to work, you should launch MC with MCEF 1.31 first (I updated the non-codec binaries just now). It will redownload the binaries.
> 
> Then, run mcef-codec-patch and apply the patches.
> 
> Make sure the skipUpdates option is set to true in the MCEF config (.minecraft/config/mcef.cfg)
> 
> You should now have proprietary codecs enabled.

Did you remove all the diffs?

**Comment by ds58** [comment]
I accidentally excluded them in .gitignore.

I readded them, sorry about that
